<?php
include __DIR__ . '/../../inc/functions.php';
include __DIR__ . '/../../inc/header.phtml';
?>
    <div class="container-fluid main-dashboard">
        <div class="col-md-12">
            <h1 class="title-header"><i class="material-icons header-icon">account_circle</i> <?=$title;?></h1>
<?php if (null !== $pages): ?>
            <div class="page-links"><?=$pages; ?></div>
<?php endif; ?>
            <nav class="btn-nav">
                <nav><a class="btn-sm text-uppercase" href="/mail/accounts/create">+ Add</a></nav>
            </nav>
<?php if (count($accounts) > 0): ?>
            <form action="/mail/accounts/delete" method="post" id="delete-form">
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th><a href="?sort=<?=getSort('id') . getQuery('sort'); ?>">#</a></th>
                            <th><a href="?sort=<?=getSort('name') . getQuery('sort'); ?>">Name</a></th>
                            <th class="text-center">Edit</th>
                            <th class="rm-col text-center"><input type="checkbox" name="check_all" id="checkAll" data-name="rm_accounts" value="" /></th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($accounts as $account): ?>
                        <tr>
                            <td><?=$account['id']; ?></td>
                            <td><?=$account['name']; ?></td>
                            <td class="text-center"><a href="/mail/accounts/<?=$account['id']; ?>"><i class="fa fa-pencil fa-lg gray-link"></i></a></td>
                            <td class="rm-col text-center"><input type="checkbox" name="rm_accounts[]" value="<?=$account['id']; ?>" /></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
                <div class="form-footer">
                    <input class="btn btn-md btn-danger text-uppercase" type="submit" value="Delete" name="submit" />
                </div>
            </form>
<?php else: ?>
            <p>There are currently no accounts.</p>
<?php endif; ?>
        </div>
    </div>
<?php include __DIR__ . '/../../inc/footer.phtml'; ?>