<?php include __DIR__ . '/../../inc/header.phtml'; ?>
    <div class="container-fluid main-dashboard">
        <div class="col-md-12">
            <h1 class="title-header"><i class="material-icons header-icon">account_circle</i> <?=$title;?></h1>
            <nav class="btn-nav">
                <nav><a class="btn-sm text-uppercase" href="/mail/accounts/create">+ Add</a></nav>
                <nav><a class="btn-sm text-uppercase" href="/mail/accounts">Back</a></nav>
            </nav>
<?=$form; ?>
        </div>
    </div>
    <div class="clearfix"></div>
<?php include __DIR__ . '/../../inc/footer.phtml'; ?>