<script src="<?=$editor; ?>"></script>
<script type="text/javascript">
    CKEDITOR.replace('message', {
        toolbarGroups: [
            { name: 'styles', groups: [ 'styles' ] },
            { name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ] },
            { name: 'paragraph', groups: [ 'list', 'align' ] },
            { name: 'links', groups: [ 'links' ] },
            { name: 'insert', groups: [ 'insert' ] },
            { name: 'clipboard', groups: [ 'clipboard', 'undo' ] },
            { name: 'editing', groups: [ 'find', 'selection', 'editing' ] },
            { name: 'colors', groups: [ 'colors' ] },
            { name: 'document', groups: [ 'mode', 'document', 'doctools' ] }
        ],
        removeButtons: 'Form,Checkbox,Radio,TextField,Textarea,Select,Button,Save,NewPage,Preview,Print,Templates,Replace,Find,ImageButton,HiddenField,Scayt,SelectAll,Superscript,Subscript,Strike,RemoveFormat,CopyFormatting,Language,BidiRtl,BidiLtr,Anchor,Flash,Table,HorizontalRule,Smiley,SpecialChar,PageBreak,Iframe,About'
    });
</script>