<?php

function generateFolderOptions($folders, $depth = 0, $parent = null, $currentFolder) {
    $depth++;

    $output = '';
    $indent = ($depth > 1) ? str_repeat('&nbsp;&nbsp;', $depth) . ' &gt; ' : '';

    foreach($folders as $folderName => $folderContent) {
        $url     = ($parent . $folderName != '[Gmail]') ? $parent . $folderName : '#';
        $output .= '<option value="' . $url . '">' . $indent . $folderName . '</option>' . PHP_EOL;
        if (!empty($folderContent['subfolders'])) {
            $output .= generateFolderOptions($folderContent['subfolders'], $depth, $parent . $folderName . '/', $currentFolder);
        }
    }

    return $output;
}

function generateFolderList($folders, $depth = 0, $parent = null, $currentFolder) {
    $depth++;

    $output = str_repeat('    ', $depth) . '<ul>' . PHP_EOL;

    foreach($folders as $folderName => $folderContent) {
        $current = (($currentFolder) == $parent . $folderName) ? ' class="current-folder"' : '';
        $url     = ($parent . $folderName != '[Gmail]') ? '/mail?folder=' . $parent . $folderName . '" onclick="$(\'#loading\').show(); return true;"' : '#" onclick="return false;"';
        $output .= str_repeat('    ', $depth) . '    <li><a href="' . $url . $current .
            '>' . '<i class="material-icons icon-sm">folder' . (($current != '') ? '_open' : '') . '</i>' . $folderName . '</a>' .
            ((!empty($folderContent['subfolders']) && ($depth < 2)) ? '<a href="#" onclick="return pop.toggleMailFolder(this);"><i class="material-icons icon-sm">expand_more</i></a>' : '');
        if (!empty($folderContent['subfolders'])) {
            $output .= PHP_EOL . generateFolderList($folderContent['subfolders'], $depth, $parent . $folderName . '/', $currentFolder) . str_repeat('    ', $depth);
        }
        $output .= '</li>' . PHP_EOL;
    }

    $output .= str_repeat('    ', $depth) . '</ul>' . PHP_EOL;

    return $output;
}

if (isset($imapFolders)):
    echo '<select id="folder-select" class="form-control form-control-sm form-control-inline">' . PHP_EOL;
    echo '    <option value="----">[Select Folder]</option>' . PHP_EOL;
    echo generateFolderOptions($imapFolders, 0, null, $currentFolder);
    echo '</select>' . PHP_EOL;
    echo generateFolderList($imapFolders, 0, null, $currentFolder);
endif;
?>
<div class="clear-both"></div>
