    <div id="add-folder-form-div" class="mail-form-div">
        <form id="add-folder-form" action="/mail/folder/add" method="post">
            <a href="#" class="form-close gray-link" onclick="return pop.closeMailForm(this);"><i class="fa fa-close"></i></a>
            <h4>Add Folder</h4>
            <div><input class="form-control form-control-sm" type="text" name="new_folder_name" id="new_folder_name" value="" placeholder=" New Folder Name" size="20" /></div>
            <div>
                <select name="add_folder_to" id="add-folder-to" class="form-control form-control-sm form-control-inline add-folder-to">
                    <option value="----">[Add Under]</option>
<?=generateFolderOptions($imapFolders, 0, null, $currentFolder); ?>
                </select>
            </div>
            <div><input class="btn btn-md btn-block btn-primary" type="submit" value="Add" /></div>
        </form>
    </div>
    <div id="rename-folder-form-div" class="mail-form-div">
        <form id="rename-folder-form" action="/mail/folder/rename" method="post">
            <a href="#" class="form-close gray-link" onclick="return pop.closeMailForm(this);"><i class="fa fa-close"></i></a>
            <h4>Rename Folder</h4>
            <div>
                <select name="folder_to_rename" id="folder-to-rename" class="form-control form-control-sm form-control-inline folder-to-rename">
                    <option value="----">[Select Folder]</option>
<?=generateFolderOptions($imapFolders, 0, null, $currentFolder); ?>
                </select>
            </div>
            <div><input class="form-control form-control-sm" type="text" name="rename_folder_to" id="rename_folder_to" value="" placeholder=" New Folder Name" size="20" /></div>
            <div><input class="btn btn-md btn-block btn-primary" type="submit" value="Rename" /></div>
        </form>
    </div>
    <div id="remove-folder-form-div" class="mail-form-div">
        <form id="remove-folder-form" action="/mail/folder/remove" method="post">
            <a href="#" class="form-close gray-link" onclick="return pop.closeMailForm(this);"><i class="fa fa-close"></i></a>
            <h4>Remove Folder</h4>
            <div>
                <select name="folder_to_remove" id="folder-to-remove" class="form-control form-control-sm form-control-inline folder-to-remove">
                    <option value="----">[Select Folder]</option>
<?=generateFolderOptions($imapFolders, 0, null, $currentFolder); ?>
                </select>
            </div>
            <div><input class="btn btn-md btn-block btn-danger" type="submit" value="Remove" /></div>
        </form>
    </div>
    <div id="advanced-search-form-div" class="mail-form-div mail-form-div-lg">
        <form id="advanced-search-form" action="/mail" method="get">
            <a href="#" class="form-close gray-link" onclick="return pop.closeMailForm(this);"><i class="fa fa-close"></i></a>
            <h4>Advanced Search</h4>
            <div>
                <label for="search_subject">Subject</label>
                <input class="form-control form-control-sm" type="text" name="search_subject" id="search_subject" value="<?php if (isset($_GET['search_subject'])): echo htmlentities(strip_tags($_GET['search_subject']), ENT_QUOTES, 'UTF-8'); endif; ?>" size="15" />
            </div>
            <div>
                <label for="search_from">From</label>
                <input class="form-control form-control-sm" type="text" name="search_from" id="search_from" value="<?php if (isset($_GET['search_from'])): echo htmlentities(strip_tags($_GET['search_from']), ENT_QUOTES, 'UTF-8'); endif; ?>" size="15" />
            </div>
            <div>
                <label for="search_text">Body</label>
                <input class="form-control form-control-sm" type="text" name="search_text" id="search_text" value="<?php if (isset($_GET['search_text'])): echo htmlentities(strip_tags($_GET['search_text']), ENT_QUOTES, 'UTF-8'); endif; ?>" size="15" />
            </div>
            <div>
                <label for="search_since">Date Since</label><label for="search_before">Date Before</label>
                <input class="form-control form-control-sm form-control-inline search-date" type="text" name="search_since" id="search_since" value="<?php if (isset($_GET['search_since'])): echo htmlentities(strip_tags($_GET['search_since']), ENT_QUOTES, 'UTF-8'); endif; ?>" placeholder="(mm/dd/yy)" size="15" /> <input class="form-control form-control-sm form-control-inline search-date pull-right" type="text" name="search_before" id="search_before" value="<?php if (isset($_GET['search_before'])): echo htmlentities(strip_tags($_GET['search_before']), ENT_QUOTES, 'UTF-8'); endif; ?>" placeholder="Date Before (mm/dd/yy)" size="15" />
            </div>
            <div>
                <select class="form-control form-control-sm" name="search_status" id="search_status">
                    <option value="----">[Status]</option>
                    <option value="SEEN"<?php if (isset($_GET['search_status']) && ($_GET['search_status'] == 'SEEN')): echo ' selected="selected"'; endif; ?>>Read</option>
                    <option value="UNSEEN"<?php if (isset($_GET['search_status']) && ($_GET['search_status'] == 'UNSEEN')): echo ' selected="selected"'; endif; ?>>Unread</option>
                </select>
            </div>
            <div><input class="btn btn-md btn-block btn-primary" type="submit" value="Search" /><input type="hidden" name="folder" value="<?=$currentFolder; ?>" /></div>
        </form>
    </div>
