            <form id="mail-search-form" action="/mail" method="get">
                <div><input class="form-control form-control-sm" type="text" name="search_subject" id="search_subject" value="<?php if (isset($_GET['search_subject'])): echo htmlentities(strip_tags($_GET['search_subject']), ENT_QUOTES, 'UTF-8'); endif; ?>" placeholder="Subject" size="15" /></div>
                <div><input class="form-control form-control-sm" type="text" name="search_from" id="search_from" value="<?php if (isset($_GET['search_from'])): echo htmlentities(strip_tags($_GET['search_from']), ENT_QUOTES, 'UTF-8'); endif; ?>" placeholder="From" size="15" /></div>
                <div>
                    <select class="form-control form-control-sm" name="search_status" id="search_status">
                        <option value="----">[Status]</option>
                        <option value="SEEN"<?php if (isset($_GET['search_status']) && ($_GET['search_status'] == 'SEEN')): echo ' selected="selected"'; endif; ?>>Read</option>
                        <option value="UNSEEN"<?php if (isset($_GET['search_status']) && ($_GET['search_status'] == 'UNSEEN')): echo ' selected="selected"'; endif; ?>>Unread</option>
                    </select>
                </div>
                <div>
                    <button type="submit" title="Search" class="btn btn-sm btn-primary search-btn"><i class="material-icons icon-sm">search</i></button>
                    <input type="hidden" name="folder" value="<?=$currentFolder; ?>" />
                    <a href="/mail?folder=<?=$currentFolder; ?>" title="Clear Search" class="btn btn-sm btn-primary search-btn"><i class="material-icons icon-sm">clear</i></a>
                    <a href="#" title="Advanced Search" class="btn btn-sm btn-primary search-btn" onclick="return pop.openMailForm('#advanced-search-form-div');"><i class="material-icons icon-sm">launch</i></a>
                </div>
            </form>
