<!DOCTYPE html>
<!-- Header //-->
<html>

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><?=$title; ?> : Pop Webmail</title>

    <link rel="stylesheet" href="//fonts.googleapis.com/icon?family=Material+Icons" />
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Source+Sans+Pro:400,300,300italic,400italic,700,700italic,900,900italic" />
    <link rel="stylesheet" type="text/css" href="/assets/app.css" />
    <link type="image/png" rel="shortcut icon" href="/assets/img/pop-webmail-icon.png"  />

</head>

<body class="login">
<?php if (isset($error)): ?>
    <h4 class="login-error"><?=$error; ?></h4>
<?php endif; ?>
    <div class="login-pad"></div>
    <div class="login-div">
<?=$form; ?>
    </div>
    <footer class="footer login-footer">
        <div>Pop Webmail v<?=\PopWebmail\Module::VERSION; ?>. &copy; <?=date('Y'); ?> <a href="https://www.nolainteractive.com/" target="_blank">NOLA Interactive</a>. All Rights Reserved.</div>
    </footer>
    <div id="loading"></div>
    <script src="/assets/app.js"></script>
</body>

</html>