<?php
include __DIR__ . '/inc/filters.php';
include __DIR__ . '/../inc/functions.php';
include __DIR__ . '/../inc/header.phtml';
?>
    <div class="container-fluid main-dashboard">
        <div class="col-md-12">
<?php if (count($accounts) > 0): ?>
            <select name="accounts_select" id="accounts_select" class="accounts-select">
<?php foreach ($accounts as $account): ?>
                <option value="<?=$account['id']; ?>"<?=($currentAccountId == $account['id']) ? ' selected="selected"' : ''; ?>><?=$account['name']; ?><?=($account['default']) ? ' (Default)' : ''?></option>
<?php endforeach; ?>
            </select>
<?php endif; ?>
            <h1 class="title-header"><i class="material-icons header-icon">email</i> <?=$title;?><?php if (!empty($mailboxTotal)): ?> (<?=$mailboxTotal; ?>)<?php endif; ?> <a href="<?=$_SERVER['REQUEST_URI']; ?>"><i class="fa fa-refresh"></i></a></h1>
<?php if (count($accounts) > 0): ?>
            <div class="clear-both">
<?php if (null !== $pages): ?>
                <div class="page-links"><?=$pages; ?></div>
<?php endif; ?>
            </div>
            <div class="mail-div">
                <div class="mail-folder-div">
<?php include __DIR__ . '/inc/folders.phtml'; ?>
                </div>
                <div class="mail-list-div">
<?php if (isset($messages) && (count($messages) > 0)): ?>
                    <form action="/mail/process" method="post" id="delete-form">
                        <table class="table table-striped table-hover">
                            <thead>
                                <tr>
                                    <th class="text-center" style="width: 50px;">&nbsp;</th>
                                    <th>Subject</th>
                                    <th class="responsive-table-column-md"><?=(stripos($currentFolder, 'sent') !== false) ? 'To' : 'From'; ?></th>
                                    <th><?=(stripos($currentFolder, 'sent') !== false) ? 'Sent' : 'Received'; ?></th>
                                    <th class="responsive-table-column-md">Size</th>
                                    <th>&nbsp;</th>
                                    <th class="rm-col text-center" style="width: 50px;"><input type="checkbox" name="check_all" id="checkAll" data-name="rm_mail" value="" /></th>
                                </tr>
                            </thead>
                            <tbody>
<?php foreach ($messages as $id => $message): ?>
                                <tr>
                                    <td class="text-center" style="width: 50px;"><a href="/mail/<?=$id; ?>" onclick="pop.openWindow(this.href, 'pab-mail', {width: 800, height: 900}); return false;"><i class="gray-link fa fa-envelope<?=((isset($message[0]) && !($message[0]->seen)) ? '' : '-open-o'); ?>"></i></a></td>
                                    <td class="small-md"><?=(isset($message[0]) && !($message[0]->seen)) ? '<strong>' : ''; ?><?=(isset($message[0]) && isset($message[0]->subject)) ? decodeText($message[0]->subject) : ''; ?><?=(isset($message[0]) && !($message[0]->seen)) ? '</strong>' : ''; ?></td>
                                    <td class="responsive-table-column-md"><?php if ((stripos($currentFolder, 'sent') !== false) && isset($message[0]) && isset($message[0]->to)):
    echo '<a href="mailto:' . filter_var(filter_var($message[0]->to, FILTER_SANITIZE_EMAIL), FILTER_VALIDATE_EMAIL) . '">' . htmlentities($message[0]->to, ENT_QUOTES, 'UTF-8') . '</a>';
elseif (isset($message[0]) && isset($message[0]->from)):
    echo '<a href="mailto:' . filter_var(filter_var($message[0]->from, FILTER_SANITIZE_EMAIL), FILTER_VALIDATE_EMAIL) . '">' . htmlentities($message[0]->from, ENT_QUOTES, 'UTF-8') . '</a>';
endif; ?></td>
                                    <td class="small no-wrap"><?=(isset($message[0]) && isset($message[0]->date)) ? date('n/j/y', strtotime($message[0]->date)) . '<span class="time-md"> ' . date('g:i A', strtotime($message[0]->date)) . '</span>': ''; ?></td>
                                    <td class="small no-wrap responsive-table-column-md"><?=(isset($message[0]) && isset($message[0]->size)) ? getFilesize($message[0]->size) : ''; ?></td>
                                    <td class="text-center"><?=(isset($message[0]) && isset($message[0]->hasAttachment) && ($message[0]->hasAttachment)) ? '<i class="fa fa-paperclip"></i>' : ''; ?></td>
                                    <td class="rm-col text-center" style="width: 50px;"><input type="checkbox" name="rm_mail[]" value="" /></td>
                                </tr>
<?php endforeach; ?>
                            </tbody>
                        </table>
                        <div class="form-footer">
                            <select id="mail_process_action" name="mail_process_action">
                                <option value="1">Mark as Read</option>
                                <option value="0">Mark as Unread</option>
                                <option value="-1">Delete</option>
                            </select>
                            <input class="btn btn-md btn-danger text-uppercase" type="submit" value="Process" name="submit" />
                        </div>
                    </form>
<?php else: ?>
                    <p>There are currently no messages in this mailbox.</p>
<?php endif; ?>
                </div>
            </div>
<?php else: ?>
            <p>There are currently no mail accounts set up. <a href="/mail/accounts/create">Add one here</a>.</p>
<?php endif; ?>
        </div>
    </div>
<?php include __DIR__ . '/../inc/footer.phtml'; ?>