<?php
include __DIR__ . '/../inc/functions.php';
include __DIR__ . '/../inc/header.phtml';
?>
    <div class="container-fluid main-dashboard">
        <div class="col-md-12">
<?php if (count($accounts) > 1): ?>
            <select name="accounts_select" id="accounts_select" class="form-control form-control-sm form-control-inline accounts-select">
<?php foreach ($accounts as $account): ?>
                <option value="<?=$account['id']; ?>"<?=($currentAccountId == $account['id']) ? ' selected="selected"' : ''; ?>><?=$account['name']; ?><?=($account['default']) ? ' (Default)' : ''?></option>
<?php endforeach; ?>
            </select>
<?php endif; ?>
            <h1 class="title-header"><?=$title;?><?php if (!empty($unread)): ?> (<?=$unread; ?>)<?php endif; ?></h1>
<?php if (count($accounts) > 0): ?>
            <div class="clear-both">
<?php if (null !== $pages): ?>
                <div class="page-links"><?=$pages; ?></div>
<?php endif; ?>
<?php if ($mailboxTotal > 0): ?>
                <h6 class="message-count"><?=$mailboxTotal; ?> Messages</h6>
<?php endif; ?>
            </div>
<?php include __DIR__ . '/inc/search.phtml'; ?>
            <div class="mail-div">
                <div class="mail-folder-div">
<?php include __DIR__ . '/inc/folders.phtml'; ?>
                    <div class="mail-nav-side-div">
<?php include __DIR__ . '/inc/mail-nav.phtml'; ?>
                    </div>
                </div>
                <div class="mail-list-div">
<?php if (isset($messages) && (count($messages) > 0)): ?>
                    <form action="/mail/process" method="post" id="mail-process-form">
                        <table class="table table-striped table-hover">
                            <thead>
                                <tr>
                                    <th class="text-center" style="width: 50px;">&nbsp;</th>
                                    <th><a href="/mail?sort=<?=getSort(3) . getQuery('sort'); ?>">Subject</a></th>
                                    <th class="responsive-table-column-lg"><a href="/mail?sort=<?=((stripos($currentFolder, 'sent') !== false) ? getSort(4) : getSort(2)) . getQuery('sort'); ?>"><?=(stripos($currentFolder, 'sent') !== false) ? 'To' : 'From'; ?></a></th>
                                    <th><a href="/mail?sort=<?=getSort(0) . getQuery('sort'); ?>">Date</a></th>
                                    <th class="responsive-table-column-lg"><a href="/mail?sort=<?=getSort(6) . getQuery('sort'); ?>">Size</a></th>
                                    <th>&nbsp;</th>
                                    <th class="rm-col text-center" style="width: 50px;"><input type="checkbox" name="check_all" id="checkAll" data-name="process_mail" value="" /></th>
                                </tr>
                            </thead>
                            <tbody>
<?php foreach ($messages as $id => $message):
    $subject      = (isset($message[0]) && isset($message[0]->subject)) ? $message[0]->subject : '';
    $shortSubject = (strlen($subject) > 20) ? substr($subject, 0, 20) . '...' : $subject;

    $emailAddress = null;
    if ((stripos($currentFolder, 'sent') !== false) && isset($message[0]) && isset($message[0]->to)):
        $emailAddress = $message[0]->to;
    elseif (isset($message[0]) && isset($message[0]->from)):
        $emailAddress = $message[0]->from;
    endif;

    if (strpos($emailAddress, '<') !== false):
        $emailAddress = substr($emailAddress, (strpos($emailAddress, '<') + 1));
        $emailAddress = substr($emailAddress, 0, strpos($emailAddress, '>'));
    endif;

    $emailAddress = filter_var(filter_var($emailAddress, FILTER_SANITIZE_EMAIL), FILTER_VALIDATE_EMAIL);
?>
                                <tr>
                                    <td class="text-center" style="width: 50px;"><a href="/mail/<?=$id; ?>" onclick="pop.openMailWindow(this.href, 'pab-mail', {width: 800, height: 900}, <?=$id; ?>); return false;"><i id="env-icon-<?=$id; ?>" class="gray-link fa fa-envelope<?=((isset($message[0]) && !($message[0]->seen)) ? '' : '-open-o'); ?>"></i></a></td>
                                    <td class="small-md"><span id="subject-span-<?=$id; ?>" class="responsive-lg<?=(isset($message[0]) && !($message[0]->seen)) ? ' bold' : ''; ?>"><?=$subject; ?></span><span class="responsive-sm"><?=$shortSubject; ?></span></td>
                                    <td class="responsive-table-column-lg"><?php if ((stripos($currentFolder, 'sent') !== false) && isset($message[0]) && isset($message[0]->to)):
    echo '<a href="/mail/compose?to=' . $emailAddress . '" onclick="pop.openWindow(this.href, \'pab-mail\', {width: 800, height: 900}); return false;"><span class="responsive-md-lg">' . htmlentities($message[0]->to, ENT_QUOTES, 'UTF-8') . '</span><span class="responsive-md">' . $emailAddress . '</span></a>';
elseif (isset($message[0]) && isset($message[0]->from)):
    echo '<a href="/mail/compose?to=' . $emailAddress . '" onclick="pop.openWindow(this.href, \'pab-mail\', {width: 800, height: 900}); return false;"><span class="responsive-md-lg">' . htmlentities($message[0]->from, ENT_QUOTES, 'UTF-8') . '</span><span class="responsive-md">' . $emailAddress . '</span></a>';
endif; ?></td>
                                    <td class="small no-wrap"><?=(isset($message[0]) && isset($message[0]->date)) ? date('n/j/y', strtotime($message[0]->date)) . '<span class="time-md"> ' . date('g:i A', strtotime($message[0]->date)) . '</span>': ''; ?></td>
                                    <td class="small no-wrap responsive-table-column-lg"><?=(isset($message[0]) && isset($message[0]->size)) ? getFilesize($message[0]->size) : ''; ?></td>
                                    <td class="text-center"><?=(isset($message[0]) && isset($message[0]->hasAttachment) && ($message[0]->hasAttachment)) ? '<i class="fa fa-paperclip"></i>' : ''; ?></td>
                                    <td class="rm-col text-center" style="width: 50px;"><input type="checkbox" name="process_mail[]" value="<?=$id; ?>" /></td>
                                </tr>
<?php endforeach; ?>
                            </tbody>
                        </table>
                        <div class="form-footer">
                            <div class="mail-nav-bottom-div">
<?php include __DIR__ . '/inc/mail-nav.phtml'; ?>
                            </div>
                            <select id="mail_process_action" name="mail_process_action" class="form-control form-control-sm form-control-inline">
                                <option value="1">Mark as Read</option>
                                <option value="0">Mark as Unread</option>
                                <option value="2">Move to Folder</option>
                                <option value="3">Copy to Folder</option>
                                <option value="-1">Move to Trash</option>
                                <option value="-2">Delete Permanently</option>
                            </select>
                            <select name="move_folder_select" id="move-folder-select" class="form-control form-control-sm form-control-inline move-folder-select">
                                <option value="----">[Select Folder]</option>
<?=generateFolderOptions($imapFolders, 0, null, $currentFolder); ?>
                            </select>
                            <input class="btn btn-md btn-danger text-uppercase process-btn" type="submit" value="Process" name="submit" /><input type="hidden" name="folder" value="<?=$currentFolder; ?>" />
                        </div>
                    </form>
<?php else: ?>
                    <p>There are currently no messages in this mailbox.</p>
<?php endif; ?>
                </div>
            </div>
<?php else: ?>
            <p>There are currently no mail accounts set up. <a href="/mail/accounts/create">Add one here</a>.</p>
<?php endif; ?>
        </div>
    </div>
<?php include __DIR__ . '/inc/mail-forms.phtml'; ?>
<?php include __DIR__ . '/../inc/footer.phtml'; ?>