<?php include __DIR__ . '/../inc/functions.php'; ?>
<?php include __DIR__ . '/../inc/header-no-nav.phtml'; ?>
    <div class="container-fluid main-dashboard">
        <div class="col-md-12">
            <div class="mail-nav">
                <a class="btn-md btn-secondary" title="Close" href="#" onclick="window.close(); return false;"><i class="fa fa-close fa-lg"></i></a>
                <a class="btn-md btn-secondary" title="Print" href="#" onclick="window.print(); return false;"><i class="fa fa-print fa-lg"></i></a>
                <a class="btn-md btn-secondary" title="Forward" href="/mail/compose?id=<?=$id; ?>&action=forward"><i class="material-icons icon-sm">forward</i></a>
                <a class="btn-md btn-secondary" title="Reply All" href="/mail/compose?id=<?=$id; ?>&action=reply_all"><i class="material-icons icon-sm">reply_all</i></a>
                <a class="btn-md btn-secondary" title="Reply" href="/mail/compose?id=<?=$id; ?>&action=reply"><i class="material-icons icon-sm">reply</i></a>
            </div>
            <table class="table mail-table" cellpadding="0" cellspacing="0" border="0">
                <thead>
                    <tr><th colspan="2"><h3 class="title-header clear-both"><?=$title;?></h3></th></tr>
                </thead>
                <tbody>

                    <tr>
                        <td>
                            <strong>To:</strong>
                        </td>
                        <td><?php
$toAddresses = [];
foreach ($message->headers->to as $to):
    if (isset($to->personal)):
        $toAddresses[] = '<a href="/mail/compose?id=' . $id . '&to=' . $to->mailbox . '@' . $to->host . '">' . $to->personal . ' &lt;' . $to->mailbox . '@' . $to->host . '&gt;</a>';
    else:
        $toAddresses[] = '<a href="/mail/compose?id=' . $id . '&to=' . $to->mailbox . '@' . $to->host . '">' . $to->mailbox . '@' . $to->host . '</a>';
    endif;
endforeach;
echo implode(', ', $toAddresses);
?></td>
                    </tr>
<?php if (isset($message->headers->cc) && (count($message->headers->cc) > 0)): ?>
                    <tr>
                        <td>
                            <strong>CC:</strong>
                        </td>
                        <td><?php
$ccAddresses = [];
foreach ($message->headers->cc as $cc):
    if (isset($cc->personal)):
        $ccAddresses[] = '<a href="/mail/compose?id=' . $id . '&to=' . $cc->mailbox . '@' . $cc->host . '">' . $cc->personal . ' &lt;' . $cc->mailbox . '@' . $cc->host . '&gt;</a>';
    else:
        $ccAddresses[] = '<a href="/mail/compose?id=' . $id . '&to=' . $cc->mailbox . '@' . $cc->host . '">' . $cc->mailbox . '@' . $cc->host . '</a>';
    endif;
endforeach;
echo implode(', ', $ccAddresses);
?></td>
                    </tr>
<?php endif; ?>
                    <tr>
                        <td>
                            <strong>From:</strong>
                        </td>
                        <td><a href="/mail/compose?id=<?=$id . '&to=' . $message->headers->from[0]->mailbox . '@' . $message->headers->from[0]->host; ?>"><?=htmlentities($message->headers->fromaddress, ENT_QUOTES, 'UTF-8'); ?></a></td>
                    </tr>
                    <tr>
                        <td><strong>Received:</strong></td>
                        <td><?=date('m/d/y g:i A', strtotime($message->headers->date)); ?></td>
                    </tr>
<?php if (count($attachments) > 0): ?>
                    <tr>
                        <td><strong>Attachments:</strong></td>
                        <td><?=implode('; ', $attachments); ?></td>
                    </tr>
<?php endif; ?>
                    <tr>
                        <td colspan="2">
<?php if (!empty($content['html']) && !empty($content['text'])): ?>
<?php if (stripos($content['html'], '<img') !== false): ?>
                            <span class="pull-right text-right small"><em>This email contains images. <a href="<?=$_SERVER['REQUEST_URI']; ?>?images=1">View images</a>.</em></span>
<?php endif; ?>
                            <ul class="nav nav-tabs mail-view-nav">
                                <li class="nav-item"><a href="#" id="html-link" class="nav-link active" onclick="return pop.showContent(this, 'html');">HTML</a></li>
                                <li class="nav-item"><a href="#" id="text-link" class="nav-link" onclick="return pop.showContent(this, 'text');">Text</a></li>
                            </ul>
                            <div id="html-content">
<?php if (!isset($_GET['images'])) :?>
<?=preg_replace('/(<*[^>]*src=)"[^>]+"([^>]*>)/', '\1""\2', $content['html']); ?>
<?php else: ?>
<?=$content['html']; ?>
<?php endif; ?>
                            </div>

                            <div id="text-content">
<?=$content['text']; ?>
                            </div>
<?php elseif (!empty($content['html'])): ?>
<?php if (stripos($content['html'], '<img') !== false): ?>
                            <span class="pull-right text-right small"><em>This email contains images. <a href="<?=$_SERVER['REQUEST_URI']; ?>?images=1">View images</a>.</em></span>
<?php endif; ?>
<?php if (!isset($_GET['images'])) :?>
<?=preg_replace('/(<*[^>]*src=)"[^>]+"([^>]*>)/', '\1""\2', $content['html']); ?>
<?php else: ?>
<?=$content['html']; ?>
<?php endif; ?>
<?php elseif (!empty($content['text'])): ?>
<?=$content['text']; ?>
<?php elseif (!empty($content['fallback'])): ?>
<?php if (stripos($content['fallback'], '<img') !== false): ?>
                            <span class="pull-right text-right small"><em>This email contains images. <a href="<?=$_SERVER['REQUEST_URI']; ?>?images=1">View images</a>.</em></span>
<?php endif; ?>
<?php if ((stripos($content['fallback'], '<img') !== false) && !isset($_GET['images'])): ?>
<?=preg_replace('/(<*[^>]*src=)"[^>]+"([^>]*>)/', '\1""\2', $content['fallback']); ?>
<?php else: ?>
<?=$content['fallback']; ?>
<?php endif; ?>
<?php endif; ?>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
<?php include __DIR__ . '/../inc/no-footer.phtml'; ?>
