<!DOCTYPE html>
<!-- Header //-->
<html>

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><?=$title; ?><?php if (!empty($mailboxTotal)): ?> (<?=$mailboxTotal; ?>)<?php endif; ?> : <?php if (isset($currentAccountName)): echo $currentAccountName . ' : '; endif; ?>Pop Webmail</title>

    <link rel="stylesheet" href="//fonts.googleapis.com/icon?family=Material+Icons" />
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Source+Sans+Pro:400,300,300italic,400italic,700,700italic,900,900italic" />
    <link rel="stylesheet" type="text/css" href="/assets/app.css" />
    <link type="image/png" rel="shortcut icon" href="/assets/img/pop-webmail-icon.png"  />

</head>

<body class="main main-no-nav">
