        <ul class="nav navbar-nav navbar-right user-nav">
            <li><a href="/profile" title="Profile"><i class="material-icons">account_box</i></a></li>
            <li><a href="/logout" title="Logout"><i class="material-icons">exit_to_app</i></a></li>
        </ul>
        <div class="logged-in">
            <h5><a href="/profile"><?=$user->username; ?></a></h5>
            <p><?=date('M j Y g:i A'); ?></p>
        </div>
